"""Write the fncall audit report."""
import os

os.makedirs(".agents/data", exist_ok=True)

LT = chr(60)
GT = chr(62)

lines = []
lines.append("# fncall Full Audit Report")
lines.append("")
lines.append("**Date:** 2026-06-06")
lines.append("**Auditor:** Automated session")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 1. Protocol Health Matrix")
lines.append("")
lines.append("| Protocol | Interpolation | Param Consistency | Schema Complete | Prompt Structure | Test Coverage | Status |")
lines.append("|----------|--------------|-------------------|-----------------|------------------|---------------|--------|")
lines.append("| xml | PASS (f-string) | lang unused but intentional | PASS (via format_tool_descs) | PASS (5 sections) | 10 tests | OK |")
lines.append("| antml | PASS (concat) | lang unused but intentional | PASS (via format_tool_descs) | PASS (5 sections) | 14 tests | OK |")
lines.append("| bracket | PASS (f-string) | lang unused but intentional | PASS (via format_tool_descs) | PASS (5 sections) | 14 tests | OK |")
lines.append("| custom | PASS (.replace) | All params used via template | N/A (user-defined) | N/A (user-defined) | 11 tests | OK |")
lines.append("| original | PASS (intentional skip) | tool_descs intentionally unused | N/A (native JSON) | 3 sections only | 12 tests | OK |")
lines.append("| nous | PASS (concat + fix) | lang unused but intentional | PASS (via format_tool_descs) | PASS (5 sections) | 14 tests | OK (already fixed) |")
lines.append("")
lines.append("### Notes")
lines.append("- **lang parameter**: No protocol currently uses lang for EN/ZH switching in render_prompt.")
lines.append("  The templates in prompt/templates.py (_USAGE_EN/_USAGE_ZH) are legacy and not referenced.")
lines.append("- **original protocol**: Intentionally does not inject tool_descs into the prompt text.")
lines.append("  It relies on platform-native JSON tool calling (codexResponses format).")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 2. Bugs Found and Fixed")
lines.append("")
lines.append("### Bug 1: inject.py Double-Wrapping (CRITICAL)")
lines.append("")
lines.append("**File:** src/core/fncall/prompt/inject.py:112-118")
lines.append("")
lines.append("**Problem:** inject_fncall() wrapped history_text, loop_warning, and current_user_message")
lines.append("in XML tags before passing to protocol.render_prompt(). Then each protocol wrapped them")
lines.append("AGAIN, producing double-nested tags like:")
lines.append("")
lines.append("    " + LT + "conversation_history" + GT)
lines.append("    " + LT + "conversation_history" + GT)
lines.append("    actual content")
lines.append("    " + LT + "/conversation_history" + GT)
lines.append("    " + LT + "/conversation_history" + GT)
lines.append("")
lines.append("**Fix:** Removed pre-wrapping in inject.py. Now passes raw values; protocols wrap themselves.")
lines.append("")
lines.append("### Bug 2: format_tool_descs No Nested Schema Rendering (IMPORTANT)")
lines.append("")
lines.append("**File:** src/core/fncall/shared/normalization.py:41-149")
lines.append("")
lines.append("**Problem:** format_tool_descs only rendered top-level parameters.")
lines.append("For type=object or type=array, it showed only the type name without recursing.")
lines.append("oneOf/anyOf/allOf and additionalProperties were silently dropped.")
lines.append("")
lines.append("**Fix:** Added _render_schema_prop() recursive helper with depth control (max 4 levels).")
lines.append("Now renders nested object properties, array items, oneOf/anyOf/allOf,")
lines.append("additionalProperties, enum, default, description at all nesting levels.")
lines.append("")
lines.append("### format_tool_descs Before/After Comparison")
lines.append("")
lines.append("**Before** (nested object only shows type=" + '"' + "object" + '"' + "):")
lines.append("")
lines.append("```")
lines.append(LT + 'parameter name="config" type="object" required="true"' + GT)
lines.append(LT + "description" + GT + "Configuration object" + LT + "/description" + GT)
lines.append(LT + "/parameter" + GT)
lines.append("```")
lines.append("")
lines.append("**After** (nested sub-properties fully rendered):")
lines.append("")
lines.append("```")
lines.append(LT + 'parameter name="config" type="object" required="true"' + GT)
lines.append(LT + "description" + GT + "Configuration object" + LT + "/description" + GT)
lines.append(LT + "properties" + GT)
lines.append('  ' + LT + 'parameter name="host" type="string" required="true"' + GT)
lines.append('  ' + LT + "description" + GT + "Server host" + LT + "/description" + GT)
lines.append('  ' + LT + "/parameter" + GT)
lines.append('  ' + LT + 'parameter name="port" type="integer" required="false"' + GT)
lines.append('  ' + LT + "description" + GT + "Server port" + LT + "/description" + GT)
lines.append('  ' + LT + "default" + GT + "8080" + LT + "/default" + GT)
lines.append('  ' + LT + "/parameter" + GT)
lines.append(LT + "/properties" + GT)
lines.append(LT + "/parameter" + GT)
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 3. Upstream Tools Passthrough Audit")
lines.append("")
lines.append("### src/routes/openai.py")
lines.append("- tools_raw passed directly to gateway.dispatch() at line 422")
lines.append("- No schema stripping or modification")
lines.append("- **Status: PASS**")
lines.append("")
lines.append("### src/routes/anthropic.py")
lines.append("- _anth_tools_to_openai() at line 286-311 converts Anthropic tools to OpenAI format")
lines.append("- Preserves full input_schema as parameters")
lines.append("- **Status: PASS**")
lines.append("")
lines.append("### src/core/dispatch/gateway.py")
lines.append("- tools passed through to inject_fncall() at line 259")
lines.append("- Full tool definitions used for prompt building and schema-aware coercion")
lines.append("- **Status: PASS**")
lines.append("")
lines.append("**Conclusion:** No upstream schema stripping found. Full JSON schemas are preserved")
lines.append("through all layers from route to protocol.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 4. Modified Files")
lines.append("")
lines.append("### Source Files")
lines.append("")
lines.append("1. **src/core/fncall/prompt/inject.py:112-118**")
lines.append("   - Fix: Removed double-wrapping of history_text, loop_warning, current_user_message")
lines.append("")
lines.append("2. **src/core/fncall/shared/normalization.py:41-149**")
lines.append("   - Fix: Added _render_schema_prop() for recursive nested schema rendering")
lines.append("   - Fix: Updated format_tool_descs() to use _render_schema_prop()")
lines.append("   - Added: _LT, _GT, _DQ, _tag(), _ctag() helpers for XML construction")
lines.append("")
lines.append("### Test Files")
lines.append("")
lines.append("3. **tests/src/core/fncall/test_xml_protocol.py**")
lines.append("   - Added: test_render_prompt_interpolates_tool_descs")
lines.append("   - Added: test_render_prompt_no_double_wrapping")
lines.append("")
lines.append("4. **tests/src/core/fncall/test_antml_protocol.py**")
lines.append("   - Added: test_render_prompt_interpolates_tool_descs")
lines.append("   - Added: test_render_prompt_no_double_wrapping")
lines.append("")
lines.append("5. **tests/src/core/fncall/test_bracket_protocol.py**")
lines.append("   - Added: test_render_prompt_interpolates_tool_descs")
lines.append("   - Added: test_render_prompt_no_double_wrapping")
lines.append("")
lines.append("6. **tests/src/core/fncall/test_custom_protocol.py**")
lines.append("   - Added: test_render_prompt_interpolates_tool_descs")
lines.append("")
lines.append("7. **tests/src/core/fncall/test_original_protocol.py**")
lines.append("   - Added: test_render_prompt_interpolates_tool_descs")
lines.append("")
lines.append("8. **tests/src/core/fncall/shared/test_shared.py**")
lines.append("   - Added: test_nested_object_properties")
lines.append("   - Added: test_array_of_objects")
lines.append("   - Added: test_oneof_anyof_schema")
lines.append("   - Added: test_additional_properties")
lines.append("   - Added: test_enum_in_parameter")
lines.append("")
lines.append("### NOT Modified (per constraints)")
lines.append("- src/core/fncall/protocols/nous.py (already fixed)")
lines.append("- tests/src/core/fncall/test_nous_protocol.py (already has regression test)")
lines.append("- config.toml, README.md, RECORD.md, SKILL.md, template/")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 5. Test Results")
lines.append("")
lines.append("### fncall subset (tests/src/core/fncall)")
lines.append("```")
lines.append("143 passed in 0.93s")
lines.append("```")
lines.append("")
lines.append("### Full suite (tests/)")
lines.append("```")
lines.append("509 passed, 33 skipped, 3 warnings in 94.66s")
lines.append("```")
lines.append("")
lines.append("### Test count changes")
lines.append("- Before: 130 fncall tests, 496 total tests")
lines.append("- After: 143 fncall tests (+13), 509 total tests (+13)")
lines.append("- New tests added:")
lines.append("  - 6 interpolation tests (one per protocol except nous which already had one)")
lines.append("  - 3 double-wrapping prevention tests (xml, antml, bracket)")
lines.append("  - 5 nested schema rendering tests (shared)")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 6. Remaining Issues")
lines.append("")
lines.append("### Non-Critical")
lines.append("")
lines.append("1. **Legacy templates unused**: src/core/fncall/prompt/templates.py contains")
lines.append("   _USAGE_EN, _USAGE_ZH, _INSTRUCTION_EN, _INSTRUCTION_ZH with {tool_descs} placeholders")
lines.append("   using .format(). These are not imported by any protocol. They could be removed")
lines.append("   or repurposed for future i18n support, but are not causing any issues.")
lines.append("")
lines.append("2. **lang parameter unused**: All protocols accept lang but none use it.")
lines.append("   If EN/ZH prompt switching is desired in the future, the infrastructure exists")
lines.append("   in the base class signature and the templates.py file.")
lines.append("")
lines.append("3. **No allOf rendering with sub-properties**: While allOf/oneOf/anyOf variants are")
lines.append("   listed with their types and descriptions, the sub-properties within each variant")
lines.append("   are not expanded. This is acceptable as these are typically used for simple unions.")
lines.append("   If deep variant expansion is needed, _render_schema_prop can be extended.")

NL = chr(10)
with open(".agents/data/fncall_full_audit.md", "w", encoding="utf-8") as f:
    f.write(NL.join(lines))
print("Report written successfully")
