[server]
version = "2.2.174"
host = "0.0.0.0"
port = 1337
debug = false
startup_force_kill_port = true

[anthropic]
api_version = "2023-06-01"

[anthropic.model_mapping]
claude-haiku-4-5-20251001 = "qwen3-coder-plus"
claude-sonnet-4-6 = "qwen3-coder-plus"

[auth]
enabled = true
keys = ["sk-provider-v2"]
group_list_type = "blacklist"
group_list = []

[gateway]
concurrent_enabled = true
concurrent_count = 3
min_tokens = 10
group_list_type = "whitelist"
group_list = ["qwen"]

[proxy]
proxy_server = "http://127.0.0.1:40000"
proxy_enabled = true
proxy_urls = ["https://freeollama.oneplus1.top"]

[platforms_proxy]
enabled_platforms = ["qwen", "ollama"]
group_list_type = "whitelist"

[platforms]
platform_list_type = "blacklist"
platform_list = ["caiyuesbk", "cerebras", "chutes", "codebuddy", "n1n", "nvidia", "openrouter", "perplexity", "deepseek", "cursor", "aitianhu2", "apiairforce", "azuretranslate", "yandextranslate", "noobkeys", "deepl", "googletranslate"]

[fncall]
protocol = "antml"
record_prompt = false
print_prompt = false
custom_prompt_en = ""
custom_prompt_zh = ""

[fncall.fncall_mapping]
qwen = "nous"

[debug]
level = "DEBUG"
color = true
access_log = false
log_name = "provider-v2"

[autoupdate]
enabled = false
branch = "dev"
interval = 300
diff_update = false
mirrors = ["https://99z.top/https://github.com/", "https://github.com/"]
