# src/platforms/n1n/adapter.py
"""N1N平台适配器"""

from __future__ import annotations

import asyncio
import logging
from typing import Any, AsyncGenerator, Dict, List, Optional, Union

import aiohttp

from src.core.candidate import Candidate
from src.core.models_cache import ModelsCache
from src.platforms.base import PlatformAdapter

logger = logging.getLogger(__name__)

# 硬编码兜底模型列表
MODELS: List[str] = [
    "gpt-5.3-codex",
    "gpt-5.3-codex-high",
    "gpt-5.3-codex-xhigh",
    "gpt-5.4-mini",
    "gpt-5.2-codex",
    "gpt-5.1",
    "gpt-5.3-codex-medium",
    "gpt-5.3-codex-spark",
    "gpt-5-codex",
    "gpt-5.1-codex",
    "gpt-5.1-codex-max",
    "gpt-5.4-medium",
    "gpt-5.4-xhigh",
    "gpt-5.3-codex-low",
    "gpt-5-codex-high",
    "gpt-5.4-high",
    "gpt-5.4-low",
    "gpt-5.2",
    "gpt-5.4",
    "gpt-5-codex-medium",
    "gpt-5.1-codex-medium",
    "gemini-2.5-flash",
    "gemini-3-flash-preview",
    "gemini-2.5-pro",
    "gemini-3-pro-preview-11-2025",
    "gemini-3-pro-preview",
    "gemini-3.1-pro-preview",
    "gemini-3-flash-preview-nothinking",
    "gpt-5-chat-2025-08-07",
    "gpt-4-vision-preview",
    "tts-1-hd",
    "gpt-5.4-pro-2026-03-05",
    "grok-4-fast",
    "gpt-4o-mini-2024-07-18",
    "gpt-4.1-mini",
    "Kimi-K2-Instruct",
    "claude-sonnet-4-5-20250929-thinking",
    "veo_3_1-fast-4K",
    "gpt-4",
    "tts-1",
    "gpt-5-pro",
    "gpt-5.2-chat-latest",
    "deepseek-v3.2-exp",
    "sora-2-pro-all",
    "veo2-fast-frames",
    "gemini-2.5-pro-all",
    "gpt-3.5-turbo-1106",
    "llama-2-7b",
    "llama-3.2-1b-instruct",
    "gpt-5-all",
    "gpt-4-32k",
    "claude-3-7-sonnet-20250219-thinking",
    "gpt-5.1-all",
    "llama-3.1-405b",
    "claude-opus-4-20250514",
    "llama-3.2-90b-vision-instruct",
    "gpt-4-1106-preview",
    "mai-ds-r1",
    "gpt-5.3-chat-latest",
    "grok-video-3",
    "veo3.1-pro-4k",
    "gpt-4-turbo-preview",
    "meta-llama/llama-4-scout",
    "claude-3-haiku-20240307",
    "gpt-4o-2024-08-06",
    "text-embedding-ada-002",
    "gpt-4o-mini-realtime-preview",
    "deepseek-r1-250120",
    "claude-opus-4-20250514-thinking",
    "gpt-4o-mini-audio-preview",
    "veo_3_1-fast-components-4K",
    "o3-pro-2025-06-10",
    "veo_3_1-components-4K",
    "veo3",
    "o1-mini-all",
    "kimi-k2",
    "grok-4",
    "deepseek-r1",
    "claude-opus-4-6-thinking",
    "grok-3-mini",
    "claude-haiku-4-5-20251001",
    "gpt-4o-search-preview-2025-03-11",
    "llama-3-8b",
    "gpt-5.1-codex-mini",
    "claude-opus-4-1-20250805",
    "gpt-image-1",
    "veo2",
    "veo3-frames",
    "gpt-4.1-nano-2025-04-14",
    "gpt-oss-120b",
    "gpt-image-1-all",
    "claude-3-5-sonnet-20240620",
    "o4-mini-all",
    "gpt-5.1-codex-2025-11-13",
    "gpt-5-pro-2025-10-06",
    "gpt-5.4-nano-2026-03-17",
    "deepseek-r1-0528",
    "claude-3-5-haiku-20241022",
    "o1-all",
    "gpt-5-chat-latest",
    "llama-3.1-405b-instruct",
    "grok-4-fast-reasoning",
    "gpt-5.1-chat-2025-11-13",
    "gpt-5",
    "gpt-4.1-mini-2025-04-14",
    "veo_3_1",
    "o1-preview-all",
    "gpt-4.5-preview-2025-02-27",
    "gpt-4-turbo",
    "gpt-oss-20b",
    "gpt-4o-mini",
    "o3-mini",
    "gpt-4o-audio-preview-2024-12-17",
    "grok-3-reasoner",
    "claude-sonnet-4-20250514",
    "codex-mini-2025-05-16",
    "o3-mini-high-all",
    "o1-pro-all",
    "claude-sonnet-4-6",
    "grok-video-3-10s",
    "gpt-4-32k-0613",
    "dall-e-3",
    "gpt-4o-mini-tts",
    "grok-3",
    "deepseek-v3",
    "claude-sonnet-4-20250514-thinking",
    "claude-3-opus-20240229",
    "gpt-5.3-chat",
    "gpt-5-mini",
    "o1",
    "o3-pro-all",
    "gpt-5-chat",
    "gpt-5.1-chat-latest",
    "gpt-5.2-2025-12-11",
    "gpt-5-pro-all",
    "gpt-5-codex-2025-09-15",
    "gpt-4-0613",
    "gpt-4o-2024-05-13",
    "o1-mini",
    "gpt-4o-mini-transcribe",
    "gpt-4o-image-vip",
    "grok-4.1",
    "grok-4.2-image",
    "deepseek-reasoner",
    "gpt-4o-all",
    "MAI-DS-R1",
    "gpt-4.1",
    "gpt-4o-realtime-preview-2024-10-01",
    "veo_3_1-components",
    "veo2-fast",
    "tts-1-hd-1106",
    "gpt-4o-mini-realtime-preview-2024-12-17",
    "gpt-5-codex-low",
    "grok-3-deepsearch",
    "deepseek-r1-searching",
    "deepseek-r1-250528",
    "llama-3-sonar-large-32k-chat",
    "kimi-k2-thinking",
    "tts-1-1106",
    "gpt-4.1-2025-04-14",
    "gpt-audio-2025-08-28",
    "gpt-5.4-pro",
    "sora-2-all",
    "llama-2-13b",
    "llama-3-70b",
    "gpt-5-chat-2025-10-03",
    "gpt-5-2025-08-07",
    "llama-3-sonar-small-32k-chat",
    "claude-opus-4-1-20250805-thinking",
    "gpt-image-1.5-all",
    "gpt-4o-realtime-preview-2025-06-03",
    "gpt-5.1-codex-max-2025-12-04",
    "gpt-4o-mini-tts-2025-12-15",
    "o1-2024-12-17",
    "o3",
    "gpt-5.2-all",
    "veo_3_1-fast",
    "gpt-5.4-nano",
    "deepseek-v3-250324",
    "grok-4-1-fast-reasoning",
    "gpt-4o-mini-audio-preview-2024-12-17",
    "gpt-4o-realtime-preview",
    "grok-4.2",
    "claude-sonnet-4-5-20250929",
    "veo3.1-components",
    "gpt-5-nano-2025-08-07",
    "deepseek-v3-0324",
    "claude-opus-4-6",
    "veo3.1-components-4k",
    "gpt-5.1-thinking-all",
    "gpt-4.5-preview",
    "grok-4-image",
    "llama-3.1-70b",
    "gpt-4o-audio-preview",
    "veo2-pro",
    "veo3.1-4k",
    "gpt-4-turbo-2024-04-09",
    "o4-mini-2025-04-16",
    "Dolphin3.0-R1-Mistral-24B",
    "sora_image",
    "veo2-fast-components",
    "o3-2025-04-16",
    "grok-4.1-image",
    "veo3-pro",
    "veo3-fast-frames",
    "o1-preview-2024-09-12",
    "babbage-002",
    "gpt-image-1.5",
    "gpt-4-all",
    "grok-4-fast-non-reasoning",
    "gpt-4o",
    "grok-4.1-fast",
    "gpt-5-codex-mini",
    "gpt-5-nano",
    "o3-mini-2025-01-31",
    "gpt-4o-realtime-preview-2024-12-17",
    "mistral-large-latest",
    "sora-2-characters",
    "gpt-5.1-2025-11-13",
    "o1-mini-2024-09-12",
    "o4-mini",
    "grok-3-image",
    "mistral-small-latest",
    "gemini-2.5-flash-all",
    "llama-3.1-70b-instruct",
    "veo3-fast",
    "veo3.1",
    "veo3.1-pro",
    "text-embedding-3-small",
    "davinci-002",
    "gpt-5.1-chat",
    "llama-2-70b",
    "veo3-pro-frames",
    "gpt-5-thinking-all",
    "gpt-5.2-chat-2025-12-11",
    "claude-3-5-sonnet-20241022",
    "claude-3-7-sonnet-20250219",
    "claude-opus-4-5-20251101-thinking",
    "llama-3.2-11b-vision-instruct",
    "text-embedding-3-large",
    "o3-all",
    "veo2-pro-components",
    "gpt-4-0125-preview",
    "gpt-4o-transcribe",
    "o3-mini-all",
    "veo_3_1-4K",
    "gpt-4.1-nano",
    "grok-3-reasoning",
    "claude-haiku-4-5-20251001-thinking",
    "llama-3.1-8b",
    "llama-3.2-3b-instruct",
    "kimi-k2-0905",
    "claude-opus-4-5-20251101",
    "veo3.1-fast-components",
    "gpt-5.2-chat",
    "gpt-5-mini-2025-08-07",
    "o1-preview",
    "gpt-5.3-chat-2026-03-03",
    "gpt-5.4-2026-03-05",
    "gpt-5.4-mini-2026-03-17",
    "deepseek-r1-2025-01-20",
    "meta-llama/llama-4-maverick",
    "o3-pro",
    "grok-4-1-fast-non-reasoning",
    "gpt-4o-mini-transcribe-2025-12-15",
    "whisper-1",
    "gpt-4o-2024-11-20",
    "veo3.1-fast",
    "gpt-4-gizmo-*",
    "qwen2.5-14b-instruct",
    "qwen3.5-plus-2026-02-15",
    "flux-pro",
    "qwen3-30b-a3b-instruct-2507",
    "MiniMax-M2.7",
    "glm-4.5-flash",
    "qwen3-vl-235b-a22b-thinking",
    "deepseek-v3.1",
    "qwen3-vl-32b-thinking",
    "deepseek-v3.2-fast",
    "qwen3-8b",
    "qwen2.5-vl-72b-instruct",
    "qwen3-vl-plus",
    "qwen-plus-latest",
    "kimi-k2-instruct",
    "SparkDesk-v3.5",
    "qwen3-vl-235b-a22b-instruct",
    "gpt-realtime",
    "qwen3-tts-flash-2025-11-27",
    "qwen2.5-14b-instruct-1m",
    "glm-4.5",
    "moonshot-v1-32k",
    "qwq-32b-preview",
    "doubao-seedance-1-0-lite-t2v-250428",
    "Embedding-V1",
    "deepseek-chat",
    "qwen2.5-math-7b-instruct",
    "MiniMax-M2.5",
    "flux.1.1-pro",
    "qwen3-30b-a3b-thinking-2507",
    "qwen-vl-max-2025-08-13",
    "qwq-32b",
    "qwen3-vl-8b-instruct",
    "qwen3-235b-a22b",
    "qwen2.5-32b-instruct",
    "qwen2.5-coder-7b-instruct",
    "qwen3-coder-480b-a35b-instruct",
    "qwen2-vl-7b-instruct",
    "doubao-seedance-1-0-pro-250528",
    "glm-4-air",
    "wen-max-2025-01-25",
    "longcat-flash-chat",
    "deepseek-v3-fast",
    "flux-dev",
    "SparkDesk-v1.1",
    "qwen2.5-coder-32b-instruct",
    "deepseek-v3.1-fast",
    "glm-4.7",
    "doubao-seedance-1-0-lite-i2v-250428",
    "doubao-seededit-3-0-i2i-250628",
    "flux-schnell",
    "qwen3-0.6b",
    "qwen3.5-397b-a17b",
    "qwen2.5-3b-instruct",
    "doubao-seedream-3-0-t2i-250415",
    "qvq-max",
    "deepseek-ocr",
    "ERNIE-4.0-8K",
    "qwen3.5-plus",
    "qwen3-vl-8b-thinking",
    "qvq-max-latest",
    "qwen2.5-72b-instruct",
    "qwen3-rerank",
    "ERNIE-Lite-8K",
    "kimi-k2-0711-preview",
    "sora-2",
    "z-image-turbo",
    "deepseek-v3.2-thinking",
    "wan2.5-i2v-preview",
    "qwen-turbo-2025-07-15",
    "qwen-flash",
    "glm-4.5-air",
    "ERNIE-Tiny-8K",
    "qwen2.5-7b-instruct",
    "qwen2.5-7b-instruct-1m",
    "qwen-image-max-2025-12-30",
    "flux-2-pro",
    "SparkDesk-v3.1",
    "deepseek-v3.2",
    "ERNIE-Speed-8K",
    "qwen2-vl-72b-instruct",
    "qwen-turbo",
    "qwen-max",
    "qwen3-next-80b-a3b-thinking",
    "qwen-image-max",
    "glm-4.6",
    "ERNIE-Character-8K",
    "qwen2.5-coder-14b-instruct",
    "qwen2.5-vl-3b-instruct",
    "qwen3-coder",
    "gpt-audio",
    "doubao-seedream-5-0-260128",
    "MiniMax-M2.1",
    "glm-4.5-airx",
    "qwen-plus-character",
    "qwen3.5-35b-a3b",
    "qwen3-coder-flash",
    "glm-4-airx",
    "glm-4.6-thinking",
    "gpt-image-1-mini",
    "qwen-image-edit-2509",
    "mimo-v2-flash",
    "doubao-seedream-4-5-251128",
    "glm-4",
    "minimax-m2",
    "deepseek-r1-distill-qwen-32b",
    "qwen3-235b-a22b-thinking-2507",
    "ERNIE-3.5-8K",
    "ERNIE-Speed-128K",
    "flux-pro-max",
    "qwen3-vl-30b-a3b-instruct",
    "qwen3-14b",
    "qwen2.5-vl-7b-instruct",
    "deepseek-v3-1-think-250821",
    "qwen3-32b",
    "kimi-k2.5",
    "deepseek-r1-distill-qwen-7b",
    "qwen3-vl-30b-a3b-thinking",
    "qwen-vl-max-latest",
    "ERNIE-Functions-8K",
    "qwen3-235b-a22b-instruct-2507",
    "qwen2.5-vl-32b-instruct",
    "qwen-plus",
    "qwen3.5-122b-a10b",
    "glm-4.7-thinking",
    "gpt-5.2-codex-2026-01-14",
    "qwen3-coder-30b-a3b-instruct",
    "qwen3-max",
    "qwen3-tts-flash",
    "moonshot-v1-8k",
    "qwen-max-latest",
    "qwen3-vl-flash",
    "flux-2-flex",
    "deepseek-v3.2-exp-thinking",
    "doubao-seedance-1-0-pro-fast-251015",
    "qwen3.5-27b",
    "glm-4-long",
    "MiniMax-M2",
    "deepseek-v3-1-250821",
    "minimax-m2.1",
    "qwen3-max-preview",
    "glm-4.6v",
    "deepseek-v3-1",
    "qwq-plus-2025-03-05",
    "qwen3-30b-a3b",
    "qwen3-max-2026-01-23",
    "gpt-4-32K-0613",
    "qwq-plus",
    "qwen2.5-math-72b-instruct",
    "glm-4.5-x",
    "deepseek-v3.1-thinking",
    "SparkDesk-v2.1",
    "qwen-plus-2025-12-01",
    "doubao-seedream-4-0-250828",
    "longcat-flash-thinking",
    "moonshot-v1-128k",
    "glm-5",
    "glm-4-flash",
    "doubao-seedance-1-5-pro-251215",
    "glm-3-turbo",
    "deepseek-v3-search",
    "flux-pro-1.1-ultra",
    "seed-oss-36b-instruct",
    "qwen3-4b",
    "qwen-vl-max",
    "kimi-k2-250905",
    "deepseek-r1-distill-llama-70b",
    "qwen3-vl-32b-instruct",
    "qwen3-next-80b-a3b-instruct",
    "qwen3-1.7b",
    "gemini-2.5-flash-preview-09-2025",
    "gemini-2.5-flash-lite-preview-09-2025",
    "gemini-2.5-flash-thinking",
    "gemini-2.5-flash-preview-05-20",
    "gemini-3.1-flash-preview",
    "gemini-2.5-pro-preview-tts",
    "gemini-embedding-001",
    "gemini-3-pro-preview-thinking",
    "gemini-3.1-flash-image-preview",
    "gemini-2.5-pro-thinking",
    "gemini-2.5-flash-image-preview",
    "gemini-3.1-pro-preview-customtools",
    "gemini-3-flash-preview-thinking",
    "gemini-3.1-flash-lite-preview",
    "gemini-2.5-flash-lite",
    "gemini-2.5-flash-lite-preview-06-17",
    "gemini-2.5-flash-preview-tts",
    "gemini-2.5-flash-image",
    "gemini-3-pro-image-preview",
    "gemini-3.1-pro-preview-thinking",
    "gemini-embedding-2-preview",
    "gemini-2.5-flash-nothinking",
    "claude-sonnet-4-20250929",
    "claude-3-sonnet-20240229",
    "claude-sonnet-4-6-thinking",
    "claude-sonnet-4-20250929-thinking",
    "claude-haiku-4-5",
    "gemma-7b-it",
    "vidu-tts",
    "Qwen/Qwen3-Reranker-0.6B",
    "suno_lyrics",
    "mj_pan",
    "mj_video",
    "mj_edits",
    "kling-image-recognize",
    "MiniMax-Hailuo-2.3",
    "qwen3-coder-plus",
    "kling-avatar-image2video",
    "viduq3-mix",
    "aigc-image-gem",
    "MiniMax-Hailuo-02",
    "mj_upscale",
    "aigc-image-qwen",
    "qwen3-max-preview-n",
    "MiniMax-Voice-Design",
    "runwayml-gen4_turbo-5",
    "netease-youdao/bce-reranker-base_v1",
    "kling-omni-video",
    "mj_variation",
    "viduq1",
    "suno_music",
    "audio1.0",
    "Pro/BAAI/bge-reranker-v2-m3",
    "qwen3-30b-a3b-think",
    "llama-3.3-70b-instruct",
    "runwayml-gen4_turbo-10",
    "grok-imagine-image-pro",
    "gpt-5.3-codex-2026-02-24",
    "viduq2",
    "speech-2.8-turbo",
    "aigc-video-hailuo",
    "speech-2.6-turbo",
    "viduq2-turbo",
    "flux.1-kontext-pro",
    "mj_inpaint",
    "sora-2-pro",
    "viduq3-turbo",
    "qwq-72b-preview",
    "mj_describe",
    "kling-motion-control",
    "kling-advanced-custom-elements",
    "suno_uploads",
    "flux-1.1-pro",
    "speech-02-turbo",
    "speech-02-hd",
    "kling-custom-elements",
    "mj_imagine",
    "kling-advanced-lip-sync",
    "viduq2-pro",
    "kling-image",
    "kling-video-extend",
    "mj_blend",
    "MiniMax-File-Upload",
    "gemma-2b-it",
    "minimax-m2.5",
    "mj_modal",
    "aigc-video-vidu",
    "gpt-5.1-codex-mini-2025-11-13",
    "MiniMax-Voice-Clone",
    "vidu2.0",
    "viduq3-pro",
    "viduq3",
    "mj_high_variation",
    "mj_reroll",
    "grok-imagine-image",
    "mj_upload",
    "gpt-realtime-1.5-2026-02-23",
    "kling-video",
    "kling-custom-voices",
    "gpt-image-1-2025-04-15",
    "mj_custom_zoom",
    "gpt-5.2-pro",
    "viduq1-classic",
    "kling-multi-elements",
    "mj_low_variation",
    "gpt-5.2-pro-2025-12-11",
    "BAAI/bge-reranker-v2-m3",
    "kling-effects",
    "speech-2.8-hd",
    "gpt-realtime-1.5",
    "mj_zoom",
    "speech-2.6-hd",
    "kling-omni-image",
    "aigc-video-kling",
    "kling-audio",
    "codex-mini-latest",
    "text-embedding-v1",
    "gpt-4o-search-preview",
    "text-curie-001",
    "gpt-4o-mini-search-preview",
    "gpt-4o-mini-search-preview-2025-03-11",
    "o1-pro",
    "text-babbage-001",
    "gpt-4o-audio-preview-2025-06-03",
    "o1-pro-2025-03-19",
    "claude-3-7-sonnet-latest",
    "gpt-5-search-api-2025-10-14",
    "gpt-5-search-api",
    "text-search-ada-doc-001",
    "sora-2-vip-all",
    "doubao-seed-1-6-thinking-250615",
    "stability-ai/stable-diffusion-inpainting",
    "prunaai/vace-14b",
    "ideogram_edit_V_3_TURBO",
    "doubao-seed-2-0-code-preview-260215",
    "black-forest-labs/flux-kontext-dev",
    "stability-ai/stable-diffusion",
    "google/imagen-4-ultra",
    "black-forest-labs/flux-dev",
    "stability-ai/sdxl",
    "ideogram_remix_V_3_TURBO",
    "doubao-seed-1-8-251228-thinking",
    "flux-kontext-apps/multi-image-kontext-pro",
    "ideogram_generate_V_1_TURBO",
    "ideogram_remix_V_2_TURBO",
    "ideogram_generate_V_1",
    "doubao-seed-1-6-flash-250828",
    "flux-kontext-apps/multi-image-kontext-max",
    "doubao-seed-2-0-pro-260215",
    "ideogram_remix_V_1",
    "ideogram_upscale",
    "ideogram_edit_V_3_QUALITY",
    "ideogram_reframe_V_3_DEFAULT",
    "doubao-seed-1-6-vision-250815",
    "black-forest-labs/flux-schnell",
    "ideogram_describe",
    "stability-ai/stable-diffusion-img2img",
    "ideogram_reframe_V_3_QUALITY",
    "google/imagen-4-fast",
    "ideogram_generate_V_3_DEFAULT",
    "ideogram-ai/ideogram-v2-turbo",
    "lucataco/animate-diff",
    "ideogram_remix_V_3_DEFAULT",
    "ideogram_reframe_V_3_TURBO",
    "black-forest-labs/flux-1.1-pro-ultra",
    "lucataco/flux-dev-lora",
    "minimax/video-01-live",
    "doubao-seed-1-6-thinking-250715",
    "cjwbw/rembg",
    "luma_video_api",
    "luma_video_extend_api",
    "doubao-seed-2-0-lite-260215",
    "black-forest-labs/flux-fill-dev",
    "black-forest-labs/flux-pro",
    "recraft-ai/recraft-v3-svg",
    "sujaykhandekar/object-removal",
    "ideogram_generate_V_3_QUALITY",
    "minimax/video-01",
    "ideogram_generate_V_2",
    "ideogram_remix_V_2",
    "recraft-ai/recraft-v3",
    "lucataco/flux-schnell-lora",
    "ideogram_remix_V_3_QUALITY",
    "ideogram_replace_background_V_3_TURBO",
    "ideogram_replace_background_V_3_QUALITY",
    "doubao-seed-1-6-251015",
    "doubao-seed-2-0-mini-260215",
    "ideogram_replace_background_V_3_DEFAULT",
    "black-forest-labs/flux-1.1-pro",
    "doubao-seed-1-8-251228",
    "riffusion/riffusion",
    "black-forest-labs/flux-fill-pro",
    "ideogram_generate_V_2_TURBO",
    "ideogram_remix_V_1_TURBO",
    "black-forest-labs/flux-kontext-pro",
    "lucataco/remove-bg",
    "google/imagen-4",
    "ideogram_generate_V_3_TURBO",
    "ideogram_edit_V_3_DEFAULT",
    "black-forest-labs/flux-kontext-max",
    "andreasjansson/stable-diffusion-animation",
    "doubao-seed-1-6-250615",
]

CAPS: Dict[str, bool] = {
    "chat": True,
}

FETCH_MODELS_ENABLED: bool = False
MODEL_FETCH_INTERVAL: int = 86400


class N1nAdapter(PlatformAdapter):
    """N1N适配器"""

    def __init__(self) -> None:
        self._client: Any = None
        self._models: List[str] = list(MODELS)
        self._cache: Optional[ModelsCache] = None
        self._refresh_task: Optional[asyncio.Task] = None

    @property
    def name(self) -> str:
        """返回平台标识。"""
        return "n1n"

    @property
    def supported_models(self) -> List[str]:
        """返回当前支持的模型列表。"""
        return list(self._models)

    @property
    def default_capabilities(self) -> Dict[str, bool]:
        """返回默认能力字典。"""
        return CAPS

    async def init(self, session: aiohttp.ClientSession) -> None:
        """初始化适配器——立即注册，后台完善。"""
        from src.platforms.n1n.client import N1nClient

        self._client = N1nClient()
        await self._client.init_immediate(session)

        self._cache = ModelsCache(
            platform="n1n",
            fallback_models=MODELS,
            fetch_enabled=FETCH_MODELS_ENABLED,
        )
        cached = await self._cache.load()
        if cached:
            self._models = cached
            self._client.update_models(self._models)

        self._refresh_task = asyncio.ensure_future(self._background_init())

    async def _background_init(self) -> None:
        """后台初始化：完成耗时操作后持续刷新。"""
        try:
            await self._client.background_setup()
        except Exception as e:
            logger.warning("n1n后台初始化失败: %s", e)

        if self._cache is not None:
            asyncio.ensure_future(
                self._cache.start_refresh_loop(
                    fetch_fn=self.fetch_remote_models,
                    interval=MODEL_FETCH_INTERVAL,
                    on_update=self._on_models_updated,
                )
            )

    async def _on_models_updated(self, models: List[str]) -> None:
        """模型列表更新回调。"""
        self._models = models
        if self._client is not None:
            self._client.update_models(models)
        logger.info("n1n模型列表已更新: %d个", len(models))

    async def fetch_remote_models(self) -> List[str]:
        """拉取远程模型列表，委托给client。"""
        if self._client is None:
            return list(MODELS)
        return await self._client.fetch_remote_models()

    async def candidates(self) -> List[Candidate]:
        """返回当前可用候选项。"""
        if self._client is None:
            return []
        return await self._client.candidates()

    async def ensure_candidates(self, count: int) -> int:
        """确保候选项数量。"""
        if self._client is None:
            return 0
        return await self._client.ensure_candidates(count)

    async def complete(
        self,
        candidate: Candidate,
        messages: List[Dict[str, Any]],
        model: str,
        stream: bool,
        *,
        thinking: bool = False,
        search: bool = False,
        **kw: Any,
    ) -> AsyncGenerator[Union[str, Dict[str, Any]], None]:
        """聊天补全，委托给client。"""
        async for chunk in self._client.complete(
            candidate, messages, model, stream,
            thinking=thinking, search=search, **kw,
        ):
            yield chunk

    async def close(self) -> None:
        """关闭适配器，释放资源。"""
        if self._refresh_task is not None and not self._refresh_task.done():
            self._refresh_task.cancel()
            try:
                await self._refresh_task
            except asyncio.CancelledError:
                pass
        if self._client is not None:
            await self._client.close()
